# Task 1: Dataset Loading & Merging

In [35]:
data_url <- "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"
test_url <- "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.test"

col_names <- c("age", "workclass", "fnlwgt", "education", "education_num",
               "marital_status", "occupation", "relationship", "race", "sex",
               "capital_gain", "capital_loss", "hours_per_week", "native_country",
               "income")

adult_data <- read.csv(data_url, header = FALSE, col.names = col_names, stringsAsFactors = FALSE)
adult_test <- read.csv(test_url, header = FALSE, col.names = col_names, stringsAsFactors = FALSE, skip = 1)

adult <- rbind(adult_data, adult_test)

# Task 2: Dataset Structure and Inspection

In [36]:
str(adult)
head(adult)

'data.frame':	48842 obs. of  15 variables:
 $ age           : int  39 50 38 53 28 37 49 52 31 42 ...
 $ workclass     : chr  " State-gov" " Self-emp-not-inc" " Private" " Private" ...
 $ fnlwgt        : int  77516 83311 215646 234721 338409 284582 160187 209642 45781 159449 ...
 $ education     : chr  " Bachelors" " Bachelors" " HS-grad" " 11th" ...
 $ education_num : int  13 13 9 7 13 14 5 9 14 13 ...
 $ marital_status: chr  " Never-married" " Married-civ-spouse" " Divorced" " Married-civ-spouse" ...
 $ occupation    : chr  " Adm-clerical" " Exec-managerial" " Handlers-cleaners" " Handlers-cleaners" ...
 $ relationship  : chr  " Not-in-family" " Husband" " Not-in-family" " Husband" ...
 $ race          : chr  " White" " White" " White" " Black" ...
 $ sex           : chr  " Male" " Male" " Male" " Male" ...
 $ capital_gain  : int  2174 0 0 0 0 0 0 0 14084 5178 ...
 $ capital_loss  : int  0 0 0 0 0 0 0 0 0 0 ...
 $ hours_per_week: int  40 13 40 40 40 40 16 45 50 40 ...
 $ native_country: chr  " United-States" " United-States" " United-States" " United-States" ...
 $ income        : chr  " <=50K" " <=50K" " <=50K" " <=50K" ...

  age workclass         fnlwgt education  education_num marital_status
1 39   State-gov         77516  Bachelors 13             Never-married
2 50   Self-emp-not-inc  83311  Bachelors 13             Married-civ-spouse
3 38   Private          215646  HS-grad    9             Divorced
4 53   Private          234721  11th       7             Married-civ-spouse
5 28   Private          338409  Bachelors 13             Married-civ-spouse
6 37   Private          284582  Masters   14             Married-civ-spouse
  occupation         relationship   race   sex     capital_gain capital_loss
1  Adm-clerical       Not-in-family  White  Male   2174         0
2  Exec-managerial    Husband        White  Male      0         0
3  Handlers-cleaners  Not-in-family  White  Male      0         0
4  Handlers-cleaners  Husband        Black  Male      0         0
5  Prof-specialty     Wife           Black  Female    0         0
6  Exec-managerial    Wife           White  Female    0         0
  hours_per_week native_country income
1 40              United-States  <=50K
2 13              United-States  <=50K
3 40              United-States  <=50K
4 40              United-States  <=50K
5 40              Cuba           <=50K
6 40              United-States  <=50K

# Task 3: Statistical Data Summary

In [37]:
summary(adult)

      age         workclass             fnlwgt         education
 Min.   :17.00   Length:48842       Min.   :  12285   Length:48842
 1st Qu.:28.00   Class :character   1st Qu.: 117550   Class :character
 Median :37.00   Mode  :character   Median : 178144   Mode  :character
 Mean   :38.64                      Mean   : 189664
 3rd Qu.:48.00                      3rd Qu.: 237642
 Max.   :90.00                      Max.   :1490400
 education_num   marital_status      occupation        relationship
 Min.   : 1.00   Length:48842       Length:48842       Length:48842
 1st Qu.: 9.00   Class :character   Class :character   Class :character
 Median :10.00   Mode  :character   Mode  :character   Mode  :character
 Mean   :10.08
 3rd Qu.:12.00
 Max.   :16.00
     race               sex             capital_gain    capital_loss
 Length:48842       Length:48842       Min.   :    0   Min.   :   0.0
 Class :character   Class :character   1st Qu.:    0   1st Qu.:   0.0
 Mode  :character   Mode  :character   Median :    0   Median :   0.0
                                       Mean   : 1079   Mean   :  87.5
                                       3rd Qu.:    0   3rd Qu.:   0.0
                                       Max.   :99999   Max.   :4356.0
 hours_per_week  native_country        income
 Min.   : 1.00   Length:48842       Length:48842
 1st Qu.:40.00   Class :character   Class :character
 Median :40.00   Mode  :character   Mode  :character
 Mean   :40.42
 3rd Qu.:45.00
 Max.   :99.00

# Task 4: Missing Value Identification and Conversion

In [38]:
any(is.na(adult))
colSums(is.na(adult))

[1] FALSE

           age      workclass         fnlwgt      education  education_num
             0              0              0              0              0
marital_status     occupation   relationship           race            sex
             0              0              0              0              0
  capital_gain   capital_loss hours_per_week native_country         income
             0              0              0              0              0

In [39]:
colSums(adult == "NULL")

           age      workclass         fnlwgt      education  education_num
             0              0              0              0              0
marital_status     occupation   relationship           race            sex
             0              0              0              0              0
  capital_gain   capital_loss hours_per_week native_country         income
             0              0              0              0              0

In [40]:
colSums(adult == -1)

           age      workclass         fnlwgt      education  education_num
             0              0              0              0              0
marital_status     occupation   relationship           race            sex
             0              0              0              0              0
  capital_gain   capital_loss hours_per_week native_country         income
             0              0              0              0              0

In [41]:
colSums(adult == "")

           age      workclass         fnlwgt      education  education_num
             0              0              0              0              0
marital_status     occupation   relationship           race            sex
             0              0              0              0              0
  capital_gain   capital_loss hours_per_week native_country         income
             0              0              0              0              0

In [42]:
colSums(adult == " ?")

           age      workclass         fnlwgt      education  education_num
             0           2799              0              0              0
marital_status     occupation   relationship           race            sex
             0           2809              0              0              0
  capital_gain   capital_loss hours_per_week native_country         income
             0              0              0            857              0

In [43]:
adult[adult == " ?"] <- NA

any(is.na(adult))
colSums(is.na(adult))

[1] TRUE

           age      workclass         fnlwgt      education  education_num
             0           2799              0              0              0
marital_status     occupation   relationship           race            sex
             0           2809              0              0              0
  capital_gain   capital_loss hours_per_week native_country         income
             0              0              0            857              0

# Task 5: Identification and Removal of Duplicate Records

In [44]:
sum(duplicated(adult))

duplicates_df <- adult[duplicated(adult) | duplicated(adult, fromLast = TRUE), ]

duplicates_ordered <- duplicates_df[order(duplicates_df$fnlwgt, duplicates_df$age), ]

head(duplicates_ordered)

adult <- unique(adult)

sum(duplicated(adult))

[1] 29

      age workclass fnlwgt education  education_num marital_status
25625 39   Private  30916   HS-grad    9             Married-civ-spouse
28847 39   Private  30916   HS-grad    9             Married-civ-spouse
7921  49   Private  31267   7th-8th    4             Married-civ-spouse
21876 49   Private  31267   7th-8th    4             Married-civ-spouse
41811 29   Private  36440   Bachelors 13             Never-married
43774 29   Private  36440   Bachelors 13             Never-married
      occupation    relationship   race   sex     capital_gain capital_loss
25625  Craft-repair  Husband        White  Male   0            0
28847  Craft-repair  Husband        White  Male   0            0
7921   Craft-repair  Husband        White  Male   0            0
21876  Craft-repair  Husband        White  Male   0            0
41811  Adm-clerical  Not-in-family  White  Female 0            0
43774  Adm-clerical  Not-in-family  White  Female 0            0
      hours_per_week native_country income
25625 40              United-States  <=50K
28847 40              United-States  <=50K
7921  40              United-States  <=50K
21876 40              United-States  <=50K
41811 40              United-States  <=50K.
43774 40              United-States  <=50K.

[1] 0

# Task 6:

# Task 7:

# Task 8:

# Task 9:

# Task 10:

# Task 11:

# Task 12:

# Task 13:

# Task 14:

# Task 15:

# Task 16:

# Task 17:

# Task 18:

# Task 19:

# Task 20:

# Task 21:

# Task 22:

# Task 23: